// Tokens de estilo compartilhados — usados em todos os componentes admin e modais

export const T = {
  // Tipografia
  heading: {
    fontFamily: "'Cinzel', serif",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: '0.06em',
    color: 'var(--brown-dark)',
  },
  label: {
    fontFamily: "'Cinzel', serif",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.05em',
    color: 'var(--muted)',
  },
  body: {
    fontFamily: "'EB Garamond', serif",
    fontSize: 15,
    color: 'var(--text)',
  },
  small: {
    fontFamily: "'EB Garamond', serif",
    fontSize: 13,
    color: 'var(--muted)',
  },

  // Cores
  gold: 'var(--gold)',
  brown: 'var(--brown)',
  brownDark: 'var(--brown-dark)',
  brownLight: 'var(--brown-light)',
  cream: 'var(--cream)',
  border: 'var(--border)',
  muted: 'var(--muted)',
  text: 'var(--text)',

  // Componentes reutilizáveis
  card: {
    backgroundColor: 'var(--cream)',
    border: '1px solid var(--border)',
    borderRadius: 12,
  },
  formCard: {
    background: 'linear-gradient(135deg,#FDF6E3,#F5E6C0)',
    border: '1px solid var(--gold)',
    borderRadius: 12,
    padding: 16,
  },
  input: {
    border: '1px solid var(--border)',
    borderRadius: 8,
    backgroundColor: '#FFF8F0',
    color: 'var(--text)',
    fontFamily: "'EB Garamond', serif",
    fontSize: 15,
    padding: '7px 12px',
    width: '100%',
    outline: 'none',
  },
  btnPrimary: {
    fontFamily: "'Cinzel', serif",
    fontSize: 11,
    letterSpacing: '0.05em',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    border: 'none',
    backgroundColor: 'var(--brown-dark)',
    color: 'var(--gold)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  btnGold: {
    fontFamily: "'Cinzel', serif",
    fontSize: 11,
    letterSpacing: '0.05em',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    border: 'none',
    backgroundColor: 'var(--gold)',
    color: 'var(--brown-dark)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  btnOutline: {
    fontFamily: "'Cinzel', serif",
    fontSize: 11,
    letterSpacing: '0.05em',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--muted)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  btnDanger: {
    fontFamily: "'Cinzel', serif",
    fontSize: 11,
    letterSpacing: '0.05em',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    border: 'none',
    backgroundColor: '#7B2020',
    color: '#FFF5F5',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: 'var(--gold)',
    flexShrink: 0,
  },
};
